receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090" # Expose metrics for Prometheus
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans" # Send traces to Zipkin
  debug:
    verbosity: detailed # Use the debug exporter for detailed logs

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, debug] # Export traces to Zipkin and log them for debugging
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug] # Export metrics for Prometheus and log them for debugging
